- name: Gather hosts
  hosts: homelab
  tasks:
    - name: Get hosts that needs bcachefs storage pool provisioning
      add_host:
        name: "{{ inventory_hostname }}"
        groups: [bcachefs_targets]
      when: is_bcachefs
    - name: Get hosts that will be nfs servers
      add_host:
        name: "{{ inventory_hostname }}"
        groups: [nfs_targets]
      when: is_nfs
    - name: Get hosts that will be samba servers
      add_host:
        name: "{{ inventory_hostname }}"
        groups: [samba_targets]
      when: is_samba

- hosts: [bcachefs_targets]
  roles:
    - role: create_storage_pool
  remote_user: root
  vars_files:
    - vars/globals.yaml

- hosts: [nfs_targets]
  roles:
    - role: provision_nfs_server
  remote_user: root
  vars_files:
    - vars/globals.yaml

- hosts: [samba_targets]
  roles:
    - role: provision_samba_server
  remote_user: root
  vars_files:
    - vars/globals.yaml
