# Playbook to provision a bcachefs storage pool.
# Assumptions:
# 1. There is only one storage pool for 1 device.
# 2. If a device (that is marked should_be_part_of_pool: True) is not part of the storage pool,
#    It will be added after the fact.

# bcachefs tools are part of GURU overlay (not in main gentoo repo)
- name: Install eselect repository tool
  community.general.portage:
    getbinpkg: true
    package: 
      - app-eselect/eselect-repository

- name: Get enabled portage overlays
  ansible.builtin.shell: eselect repository list -i
  register: enabled_overlays
  ignore_errors: true

- name: Enable GURU overlay
  when:
    -  G_GURU not in enabled_overlays.stdout
    -  G_GURU_REPO not in enabled_overlays.stdout
  block:
    - name: Enable GURU overlay
      ansible.builtin.shell:
        cmd: eselect repository enable guru
    
    - name: Sync with guru repo
      ansible.builtin.shell:
        cmd: emerge --sync guru

- name: Setup bcachefs USE flags
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ G_PORTAGE_ACCEPT_KEYWORDS_DIR }}/{{ item }}"
    mode: "0755"
    owner: "root"
  with_items:
    - bcachefs

- name: Install bcachefs tools
  community.general.portage:
    getbinpkg: true
    package: 
      - bcachefs-kmod
      - sys-fs/bcachefs-tools

- name: Collect storages that should be part of storage pool
  set_fact:
    storages_should_be_in_pool: "{{ storages | selectattr('should_be_part_of_pool') | list | default([]) }}"

- name: Check if devices are part of the storage pool
  ansible.builtin.shell: "bcachefs show-super {{ item.dev }}"
  loop: "{{ storages_should_be_in_pool }}"
  register: dev_show_super_results
  failed_when: False

- name: Check if there is already a storage pool that exists
  ansible.builtin.set_fact:
    a_pool_already_exists: "{{ dev_show_super_results.results | selectattr('rc', 'equalto', 0) | list | length > 0 }}"

- name: Get storages that are not part of storage pool
  ansible.builtin.set_fact:
    storages_not_part_of_a_storage_pool: "{{ dev_show_super_results.results | selectattr('rc', 'ne', 0) | map(attribute='item') | list }}"

- name: Create bcachefs storage pool
  when:  not a_pool_already_exists
  block:

    - name: Construct flags
      set_fact:
        bcachefs_flags: >-
          {% set result = [] %}
          {%- for s in storages_not_part_of_a_storage_pool -%}
            {{ result.append('--label=' ~ s.label ~ ' ' ~ s.dev) }}
          {%- endfor -%}
          {{ result | join(' ')}}
        bcachefs_dev:
          "{{ storages_not_part_of_a_storage_pool | map(attribute='dev') | join(':')  }}"

    - name: Check if storages to be bcachefs'ed has a fast storage (nvme)
      set_fact:
        has_nvme:
          "{{ storages_not_part_of_a_storage_pool | map(attribute='label') | select('search', 'nvme') | list | length > 0 }}"

    - name: Add storage tiering flags
      when: has_nvme
      block:
        - name: Append SSD caching flags
          set_fact:
            bcachefs_flags: "{{ bcachefs_flags }} --foreground_target=nvme --promote_target=nvme --metadata_target=nvme"

    - name: Create bcachefs RAID0 storage pool
      ansible.builtin.shell:
        cmd: bcachefs format --force --uuid={{ storage_array_uuid }} {{ bcachefs_flags }}

- name: Mount array to mount point
  ansible.builtin.include_role:
    name: common
    tasks_from: mount_storage_pool.yaml

- name: Onboard new should_be_part_of_pool storages when the storage pool already exists
  when: a_pool_already_exists and storages_not_part_of_a_storage_pool | length > 0
  block:

    - name: Onboard storages not part of pool
      ansible.builtin.shell:
        cmd: bcachefs device add --label={{ item.label }} {{ mount_point }} {{ item.dev }}
      loop: "{{ storages_not_part_of_a_storage_pool }}"
