- name: Install nfs tools
  community.general.portage:
    getbinpkg: true
    package: 
      - net-fs/nfs-utils

- name: Make sure base mount point is created and mounted
  ansible.builtin.include_role:
    name: common
    tasks_from: mount_storage_pool.yaml

- name: Get virtual and non-virtual root exports
  set_fact:
    virtual_root_exports:
      "{{ nfs_exports | select('search', 'fsid=0') | list | default([]) }}"
    non_virtual_root_exports:
      "{{ nfs_exports | reject('search', 'fsid=0') | list | default([]) }}"

- name: Create virtual root export
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0655'
  with_items: "{{ virtual_root_exports | map('split') | map('first') | unique }}"

- name: Mark non-virtual-root exports modifiable by everyone
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  with_items: "{{ non_virtual_root_exports | map('split') | map('first') | unique }}"

- name: Copy nfs server configuration
  ansible.builtin.copy:
    src: nfs.conf
    dest: /etc/nfs.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload nfs
    - reload nfs services

- name: Copy exports file.
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload nfs
    - reload nfs services

- name: Enable NFS server services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - rpcbind
    - nfs-server

